### ISSUE TITLE
Unable to only generate HTML

### ISSUE THREAD

**Issue by lucasweb78** [tomaz/appledoc#132]
I am trying to use appledoc to only generate HTML content. I do not want the docset created installed.

I am using the following arguments:

appledoc --project-name IOSCoreSDK --project-company "test" --company-id com.test --create-html YES --create-docset NO  --output ~/Workspace/iOS/IOSCoreSDK/Docs --print-settings ~/Workspace/iOS/IOSCoreSDK/

When I execute this the docset is created and installed and the HTML files are moved to the docset install location.

Below is the output of print-settings:

Running for files in locations:
- /Users/lucasr/Workspace/iOS/IOSCoreSDK/

Settings used for this run:
--project-name = IOSCoreSDK
--project-version = 1.0
--project-company = Deluxe Digital Distribution
--company-id = com.deluxe.d3

--templates = /Users/lucasr/Library/Application Support/appledoc
--output = /Users/lucasr/Workspace/iOS/IOSCoreSDK/Docs
--index-desc = (null)
--docset-install-path = /Users/lucasr/Library/Developer/Shared/Documentation/DocSets
--docsetutil-path = /Developer/usr/bin/docsetutil

--docset-bundle-id = com.deluxe.d3.IOSCoreSDK
--docset-bundle-name = IOSCoreSDK Documentation
--docset-desc = 
--docset-copyright = Copyright © 2011 Deluxe Digital Distribution. All rights reserved.
--docset-feed-name = IOSCoreSDK Documentation
--docset-feed-url = 
--docset-package-url = 
--docset-fallback-url = 
--docset-publisher-id = com.deluxe.d3.documentation
--docset-publisher-name = Deluxe Digital Distribution
--docset-min-xcode-version = 3.0
--docset-platform-family = 
--docset-cert-issuer = 
--docset-cert-signer = 
--docset-bundle-filename = com.deluxe.d3.IOSCoreSDK.docset
--docset-atom-filename = com.deluxe.d3.IOSCoreSDK.atom
--docset-package-filename = com.deluxe.d3.IOSCoreSDK-1.0.xar

--clean-output = NO
--create-html = YES
--create-docset = YES
--install-docset = YES
--publish-docset = NO
--keep-intermediate-files = NO
--keep-undocumented-objects = NO
--keep-undocumented-members = NO
--search-undocumented-doc = YES
--repeat-first-par = YES
--merge-categories = YES
--keep-merged-sections = NO
--prefix-merged-sections = NO
--crossref-format = <?%@>?
--exit-threshold = 0

--warn-missing-output-path = YES
--warn-missing-company-id = YES
--warn-undocumented-object = YES
--warn-undocumented-member = YES
--warn-empty-description = YES
--warn-unknown-directive = YES
--warn-invalid-crossref = YES
--warn-missing-arg = YES

--logformat = 1
--verbose = 2

It does not seem to honor the create-docset NO. Am I doing something wrong or is this an issue.

**Comment by rah1991** [comment]
@tomaz 
I am unable to generate any output. I am using the following command
APPLEDOC_PATH=`/Users/indianic/Desktop/MyDoc`
if [ $APPLEDOC_PATH ]; then
$APPLEDOC_PATH \
--project-name ${PRODUCT_NAME} \
--project-company "Test" \
--company-id "com.test" \
--output ${PRODUCT_NAME}Docs \
--keep-undocumented-objects \
--keep-undocumented-members \
--keep-intermediate-files \
--no-repeat-first-par \
--no-warn-invalid-crossref \
--exit-threshold 2 \
${PROJECT_DIR}/${PRODUCT_NAME}
fi;

No folder is created on desktop. Please help.

**Comment by tomaz** [comment]
Your APPLEDOC_PATH looks suspicious - it points to what seems to be MyDoc folder on Desktop but should be path to appledoc binary.

**Comment by rah1991** [comment]
@tomaz 
I have rectified my script as below. Still I am unable to see any doc folder in my project folder. What am I missing?
APPLEDOC_PATH=`/usr/local/bin/`
if [ $APPLEDOC_PATH ]; then
$APPLEDOC_PATH \
--project-name ${PROJECT_NAME} \
--project-company "YourCompany" \
--company-id "com.yourcompany" \
--ignore ".m" \
--ignore "Pods" \
--explicit-crossref \
--keep-undocumented-objects \
--keep-undocumented-members \
--no-repeat-first-par \
--no-warn-missing-arg \
--no-warn-undocumented-object \
--no-warn-undocumented-member \
--no-warn-empty-description \
--docset-bundle-id ${PROJECT_NAME} \
--docset-bundle-name ${PROJECT_NAME} \
--docset-install-path ${PROJECT_DIR} \
--output ${TEMP_DIR}  \
${PROJECT_DIR} \
> ${PROJECT_DIR}/docset-generation.log 2>&1 &
fi

I have put appledoc at following path - /usr/local/bin/

**Comment by tomaz** [comment]
APPLEDOC_PATH should be path to appledoc binary, not enclosing folder, try: `APPLEDOC_PATH=/usr/local/bin/appledoc` (if still doesn't work, try `which appledoc` to find out location of the binary - if it doesn't print out the path, then appledoc may not be installed correctly or in path)

**Comment by AngusLang** [comment]
There isn't any doc file wrote in the doc directory.
`appledoc --clean-output --no-create-docset -o ./doc -p xxx -c xx .`
the directory appear likes that.
`lang:PHMKit lang$ ls -R doc
html

doc/html:
css	img	js

doc/html/css:
scss		style.css

doc/html/css/scss:
_index.scss	_layout.scss	_normalize.scss	_object.scss	_print.scss	_variables.scss	_xcode.scss	style.scss

doc/html/img:
button_bar_background.png	disclosure_open.png		title_background.png
disclosure.png			library_background.png

doc/html/js:
script.js`
what is wrong with that, please get help.

**Comment by tomaz** [comment]
I'd check if templates are correctly installed - you can manually copy them from appledoc sources.
