### ISSUE TITLE
Failed to generate doc

### ISSUE THREAD

**Issue by nvkv** [tomaz/appledoc#211]
Hi there. Appledoc installed from Homebrew with --HEAD.

<pre>
dev/iphone [master]:λ appledoc --project-name Gipis --project-company "Hoswood" --company-id com.hoswood --ignore ThirdParty --output ./Docs --clean-output --create-html --no-create-docset ./Classes
appledoc version: 2.0.5 (build 789)

2012-04-18 18:03:29.239 appledoc[72380:707] *** Assertion failure in +[GBMethodData methodDataWithType:result:arguments:], /tmp/homebrew-appledoc-HEAD-iRKQ/Model/GBMethodData.m:39
Oops, something went wrong...
NSInternalInconsistencyException: Invalid parameter not satisfying: [arguments count] >= 1
  @ 0   CoreFoundation                      0x00007fff8b2a3fc6 __exceptionPreprocess + 198
  @ 1   libobjc.A.dylib                     0x00007fff85204d5e objc_exception_throw + 43
  @ 2   CoreFoundation                      0x00007fff8b2a3dfa +[NSException raise:format:arguments:] + 106
  @ 3   Foundation                          0x00007fff8cab9743 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 169
  @ 4   appledoc                            0x00000001037a6bdf appledoc + 89055
  @ 5   appledoc                            0x000000010379f19d appledoc + 57757
  @ 6   appledoc                            0x00000001037a2175 appledoc + 70005
  @ 7   appledoc                            0x000000010379edd3 appledoc + 56787
  @ 8   appledoc                            0x000000010379e6d9 appledoc + 55001
  @ 9   appledoc                            0x000000010379e5d9 appledoc + 54745
  @ 10  appledoc                            0x00000001037a2175 appledoc + 70005
  @ 11  appledoc                            0x000000010379e59d appledoc + 54685
  @ 12  appledoc                            0x000000010379e2dc appledoc + 53980
  @ 13  appledoc                            0x000000010379eae5 appledoc + 56037
  @ 14  appledoc                            0x000000010379e882 appledoc + 55426
  @ 15  appledoc                            0x000000010379c7ff appledoc + 47103
  @ 16  appledoc                            0x000000010379adb1 appledoc + 40369
  @ 17  appledoc                            0x000000010379bbfd appledoc + 44029
  @ 18  appledoc                            0x000000010379bd42 appledoc + 44354
  @ 19  appledoc                            0x000000010379ab2f appledoc + 39727
  @ 20  appledoc                            0x0000000103793d6e appledoc + 11630
  @ 21  appledoc                            0x00000001037929ea appledoc + 6634
  @ 22  appledoc                            0x0000000103792b48 appledoc + 6984
  @ 23  appledoc                            0x0000000103792034 appledoc + 4148
</pre>

**Comment by Mondaydream** [comment]
I had meet this error

**Comment by Mondaydream** [comment]
the same error 

2017-10-24 15:43:23.853 appledoc[68842:959507] *** Assertion failure in +[GBMethodData methodDataWithType:result:arguments:], /tmp/appledoc-20160926-59019-m3d8uj/appledoc-2.2.1/Model/GBMethodData.m:44
appledoc version: 2.2.1 (build 1333)
