### ISSUE TITLE
GBDocSetPublishGenerator failed generating output, 

### ISSUE THREAD

**Issue by ghost** [tomaz/appledoc#407]
Preparing DocSet for publishing...
GBDocSetPublishGenerator is generating output...
Initializing directory at '~/help/publish'...
Enumerating directory contents...
Generation step 5/5 failed: GBDocSetPublishGenerator failed generating output, aborting!
The folder “publish” doesn’t exist.
The folder doesn’t exist.

Could you help me solve this issue?

**Comment by kevinlishuai** [comment]
GBDocSetInstallGenerator failed generating output, aborting!
