### ISSUE TITLE
Can't install appledoc with homebrew. 'No available formula for appledoc'

### ISSUE THREAD

**Issue by Tylerc230** [tomaz/appledoc#478]
I ran `brew update` and then `brew install appledoc` and I receive "No available formula for appledoc"
Running brew search apple revealed 
"appledoc20  appledoc21  appledoc22"

running `brew install appledoc22` gave the error:
"Error: appledoc22 cannot be built with any available compilers.  
To install this formula, you may need to:  
 brew install gcc"

Maybe this is not a bug and simply needs to be mentioned in the readme. I am running maverics and Xcode 5.1.1.

**Comment by xhp281** [comment]
I think use "sudo brew install appledoc22" is ok.

**Comment by groue** [comment]
> You might consider removing brew install appledoc from the readme, because it doesn't work anymore on Yosemite and newest Homebrew

:+1:
