### ISSUE TITLE
brew install failure

### ISSUE THREAD

**Issue by jjangg96** [tomaz/appledoc#500]
home-brew said SHA1 mismatch.
I attached a log for sure.

==> Installing appledoc22 from homebrew/homebrew-versions
==> Downloading https://github.com/tomaz/appledoc/archive/v2.2.tar.gz
###### ################################################################## 100.0%

Error: SHA1 mismatch
Expected: 4ad475ee6bdc2e34d6053c4e384aad1781349f5e
Actual: b427506bdefc97b224fd0f873ff87b8d11ce4aec
Archive: /Library/Caches/Homebrew/appledoc22-2.2.tar.gz
To retry an incomplete download, remove the file above.

**Comment by michaelpatzer** [comment]
I'm also seeing this failure. Removing the file at `/Library/Caches/Homebrew/appledoc22-2.2.tar.gz` does not resolve the issue.

**Comment by sprohaszka** [comment]
I recently installed Appledoc 2.2.1 from brew and I didn't get it. Do you still have it ?

**Comment by tomaz** [comment]
You can download 2.2.1 from https://github.com/tomaz/appledoc/releases
