### ISSUE TITLE
Can we get the new releases on Homebrew?

### ISSUE THREAD

**Issue by Ashton-W** [tomaz/appledoc#505]
There have been some problems with appledoc on homebrew in the past, and I don't see the latest release on there (there isn't even a formula named just 'appledoc').

Currently the best place to get appledoc is from the [Releases page on GitHub](https://github.com/tomaz/appledoc/releases).

What needs to happen to get the binary releases back on Homebrew? Do we need to look at [Homebrew Cask]( http://caskroom.io) instead?

**Comment by tomaz** [comment]
Homebrew support was user contribution, I never "officially" supported it. I also never took the time to investigate how formulas work. If you're interested, feel free to persue this path. Of course I can help with appledoc side of things if you have any question on the way.
