### ISSUE TITLE
C functions inside Obj-C @implementation cause assertion failure

### ISSUE THREAD

**Issue by rjstelling** [tomaz/appledoc#508]
On running my project this morning `appledoc` is crashing with the following error:

>2015-02-02 11:43:49.585 appledoc[2720:1364470] *** Assertion failure in +[GBMethodData methodDataWithType:result:arguments:], /Users/rjstelling/Desktop/appledoc-master/Model/GBMethodData.m:44
>appledoc version: 2.2.1 (build 1333)

>NSInternalInconsistencyException: Invalid parameter not satisfying: [arguments count] >= 1

I'm running this command in the as an external build tool:

     /usr/local/bin/appledoc --project-name SECRETPROJECT --project-company MasterCard\ Labs --company-id com.mastercard.labs --output /Users/rjstelling/Documents/SECRETPROJECT-iphone/docs --ignore .h --no-create-docset --exit-threshold 2 ./SECRETPROJECT

It was working on Friday?

Stack Trace:

	Oops, something went wrong...
	NSInternalInconsistencyException: Invalid parameter not satisfying: [arguments count] >= 1
	  @ 0   CoreFoundation                      0x00007fff90f3966c __exceptionPreprocess + 172
	  @ 1   libobjc.A.dylib                     0x00007fff865a376e objc_exception_throw + 43
	  @ 2   CoreFoundation                      0x00007fff90f3944a +[NSException raise:format:arguments:] + 106
	  @ 3   Foundation                          0x00007fff8b4943a9 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	  @ 4   appledoc                            0x00000001040061e1 appledoc + 143841
	  @ 5   appledoc                            0x0000000103ffaa45 appledoc + 96837
	  @ 6   appledoc                            0x0000000103fffce5 appledoc + 117989
	  @ 7   appledoc                            0x0000000103ffa453 appledoc + 95315
	  @ 8   appledoc                            0x0000000103ff78ea appledoc + 84202
	  @ 9   appledoc                            0x0000000103ff77f0 appledoc + 83952
	  @ 10  appledoc                            0x0000000103fffce5 appledoc + 117989
	  @ 11  appledoc                            0x0000000103fffae5 appledoc + 117477
	  @ 12  appledoc                            0x0000000103ff776d appledoc + 83821
	  @ 13  appledoc                            0x0000000103ff7362 appledoc + 82786
	  @ 14  appledoc                            0x0000000103ff9fca appledoc + 94154
	  @ 15  appledoc                            0x0000000103ff7ae1 appledoc + 84705
	  @ 16  appledoc                            0x0000000103ff4c76 appledoc + 72822
	  @ 17  appledoc                            0x0000000103ff2942 appledoc + 63810
	  @ 18  appledoc                            0x0000000103ff3f7d appledoc + 69501
	  @ 19  appledoc                            0x0000000103ff3c3d appledoc + 68669
	  @ 20  appledoc                            0x0000000103ff3857 appledoc + 67671
	  @ 21  appledoc                            0x0000000103ff25ef appledoc + 62959
	  @ 22  appledoc                            0x0000000103fe714a appledoc + 16714
	  @ 23  appledoc                            0x0000000103fe5983 appledoc + 10627
	  @ 24  appledoc                            0x0000000103fe5aec appledoc + 10988
	  @ 25  appledoc                            0x0000000103fe5c77 appledoc + 11383
	  @ 26  appledoc                            0x0000000103fe4f34 appledoc + 7988
	  @ 27  ???                                 0x000000000000000f 0x0 + 15
	Command /usr/local/bin/appledoc failed with exit code 250

**Comment by rjstelling** [comment]
Run with verbose level 6, looks like an issue with TIToken (I added this this morning), here is a link to the git hub project: [https://github.com/thermogl/TITokenField](https://github.com/thermogl/TITokenField):

	VERBOSE | Matched TIToken class declaration at line 1072.
	DEBUG | Resetting comments...
	DEBUG | Resetting comments...
	DEBUG | Matched method -initWithTitle: at line 1083.
	DEBUG | TIToken: Registering method initWithTitle:...
	DEBUG | TIToken: Registering section default...
	DEBUG | Resetting comments...
	DEBUG | Matched method -initWithTitle:representedObject: at line 1087.
	DEBUG | TIToken: Registering method initWithTitle:representedObject:...
	DEBUG | Resetting comments...
	DEBUG | Matched method -initWithTitle:representedObject:font: at line 1091.
	DEBUG | TIToken: Registering method initWithTitle:representedObject:font:...
	DEBUG | Resetting comments...
	DEBUG | Matched method -setHighlighted: at line 1114.
	DEBUG | TIToken: Registering method setHighlighted:...
	DEBUG | Resetting comments...
	DEBUG | Matched method -setSelected: at line 1122.
	DEBUG | TIToken: Registering method setSelected:...
	DEBUG | Resetting comments...
	DEBUG | Matched method -setTitle: at line 1130.
	DEBUG | TIToken: Registering method setTitle:...
	DEBUG | Resetting comments...
	DEBUG | Matched method -setFont: at line 1139.
	DEBUG | TIToken: Registering method setFont:...
	DEBUG | Resetting comments...
	DEBUG | Matched method -setTintColor: at line 1150.
	DEBUG | TIToken: Registering method setTintColor:...
	DEBUG | Resetting comments...
	DEBUG | Matched method -setAccessoryType: at line 1160.
	DEBUG | TIToken: Registering method setAccessoryType:...
	DEBUG | Resetting comments...
	DEBUG | Matched method -setMaxWidth: at line 1169.
	DEBUG | TIToken: Registering method setMaxWidth:...
	DEBUG | Resetting comments...
	DEBUG | Matched method +blueTintColor at line 1180.
	DEBUG | TIToken: Registering method blueTintColor...
	DEBUG | Resetting comments...
	DEBUG | Matched method +redTintColor at line 1184.
	DEBUG | TIToken: Registering method redTintColor...
	DEBUG | Resetting comments...
	DEBUG | Matched method +greenTintColor at line 1188.
	DEBUG | TIToken: Registering method greenTintColor...
	DEBUG | Resetting comments...
	DEBUG | Matched method -sizeThatFits: at line 1193.
	DEBUG | TIToken: Registering method sizeThatFits:...
	DEBUG | Resetting comments...
	DEBUG | Matched method -drawRect: at line 1209.
	DEBUG | TIToken: Registering method drawRect:...
	DEBUG | Resetting comments...
	DEBUG | Resetting comments...
	2015-02-02 11:56:18.315 appledoc[2927:1431220] *** Assertion failure in +[GBMethodData methodDataWithType:result:arguments:], /Users/rjstelling/Desktop/appledoc-master/Model/GBMethodData.m:44
	Oops, something went wrong...
	NSInternalInconsistencyException: Invalid parameter not satisfying: [arguments count] >= 1
	  @ 0   CoreFoundation                      0x00007fff90f3966c __exceptionPreprocess + 172
	  @ 1   libobjc.A.dylib                     0x00007fff865a376e objc_exception_throw + 43
	  @ 2   CoreFoundation                      0x00007fff90f3944a +[NSException raise:format:arguments:] + 106
	  @ 3   Foundation                          0x00007fff8b4943a9 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	  @ 4   appledoc                            0x0000000100fed1e1 appledoc + 143841
	  @ 5   appledoc                            0x0000000100fe1a45 appledoc + 96837
	  @ 6   appledoc                            0x0000000100fe6ce5 appledoc + 117989
	  @ 7   appledoc                            0x0000000100fe1453 appledoc + 95315
	  @ 8   appledoc                            0x0000000100fde8ea appledoc + 84202
	  @ 9   appledoc                            0x0000000100fde7f0 appledoc + 83952
	  @ 10  appledoc                            0x0000000100fe6ce5 appledoc + 117989
	  @ 11  appledoc                            0x0000000100fe6ae5 appledoc + 117477
	  @ 12  appledoc                            0x0000000100fde76d appledoc + 83821
	  @ 13  appledoc                            0x0000000100fde362 appledoc + 82786
	  @ 14  appledoc                            0x0000000100fe0fca appledoc + 94154
	  @ 15  appledoc                            0x0000000100fdeae1 appledoc + 84705
	  @ 16  appledoc                            0x0000000100fdbc76 appledoc + 72822
	  @ 17  appledoc                            0x0000000100fd9942 appledoc + 63810
	  @ 18  appledoc                            0x0000000100fdaf7d appledoc + 69501
	  @ 19  appledoc                            0x0000000100fdac3d appledoc + 68669
	  @ 20  appledoc                            0x0000000100fda857 appledoc + 67671
	  @ 21  appledoc                            0x0000000100fd95ef appledoc + 62959
	  @ 22  appledoc                            0x0000000100fce14a appledoc + 16714
	  @ 23  appledoc                            0x0000000100fcc983 appledoc + 10627
	  @ 24  appledoc                            0x0000000100fccaec appledoc + 10988
	  @ 25  appledoc                            0x0000000100fccc77 appledoc + 11383
	  @ 26  appledoc                            0x0000000100fcbf34 appledoc + 7988

**Comment by rjstelling** [comment]
Here is line 1209: 

![screenshot 2015-02-02 12 01 52](https://cloud.githubusercontent.com/assets/207455/6000189/f32b9c2c-aad2-11e4-9e7a-8fee984911e2.png)

**Comment by rjstelling** [comment]
It seems to be 2 C functions that are inside the Obj-C @implementation, they are after -drawRect:

1. CGPathCreateTokenPath
2. CGPathCreateDisclosureIndicatorPath

**Comment by tomaz** [comment]
This might be the cause of crash: v2 is rather picky with its expactations of what can be inside @interface and @implementation. Move those functions outside and it should be fine

**Comment by rjstelling** [comment]
I did that, and It's fixed.
