### ISSUE TITLE
Anonymous parameters in block typedef causes whole header file not to be parsed

### ISSUE THREAD

**Issue by cnowacek** [tomaz/appledoc#514]
Appledoc will not parse your file if it has a block typedef without parameter names:

`typedef UICollectionViewCell *(^CTCollectionCellForIndexPathBlock)(UICollectionView *, CTBaseModel *, NSIndexPath *);`

Appledoc will not pick up any documentation within the file if these exist in the header (.h). Instead you must provide parameter names in the typedef like: 

`typedef UICollectionViewCell *(^CTCollectionCellForIndexPathBlock)(UICollectionView *collectionView, CTBaseModel *baseModel, NSIndexPath *indexPath)`

**Comment by jerrypainter** [comment]
nice!

**Comment by MichaelMcGuire** [comment]
Wow, great catch.  Was just having this problem.
