### ISSUE TITLE
Installing binary to /usr/local/bin/  -- "does not exist"

### ISSUE THREAD

**Issue by ghulammustafa** [tomaz/appledoc#520]
```
git clone git://github.com/tomaz/appledoc.git
```

> Successful!

```
sudo sh install-appledoc.sh
```

> ** INSTALL SUCCEEDED **

> Installing binary to /usr/local/bin/
> cp: directory /usr/local/bin does not exist

I'm unable to use appledoc because of the issue indicated above.

p.s. I'm using Mac OS X 10.10, Xcode 6.2.

**Comment by ghulammustafa** [comment]
Manually copying appledoc to /usr/bin seems to work, but the script should be updated.

**Comment by themackworth** [comment]
You can also just create the ` /usr/local/bin` directory and then add the path to `/etc/paths` which should fix the script for you.

**Comment by kenorb** [comment]
Btw., instead of:

    echo "Installing binary to $BINARY_DIR"
    cp /tmp/appledoc.dst/usr/local/bin/appledoc "$BINARY_DIR"

you can also use:

    install -v /tmp/appledoc.dst/usr/local/bin/appledoc "$BINARY_DIR"

so it's more standarized and no need for echoing message.

**Comment by Coeur** [comment]
@kenorb Applying your suggestion with 12dd17471508624bd9d0b0006aa5d9da9959cc0f
