### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by mkantor** [tomaz/appledoc#522]
Since v2.2-963 it looks like [appledoc has had some major changes](https://github.com/tomaz/appledoc/compare/v2.2-963...master). v2.2-963 can't even be compiled by XCode > 5.0. Perhaps it's time for a new release?

Part of my reason for asking is that it would be nice to get appledoc out of [the homebrew graveyard](https://github.com/Homebrew/homebrew-boneyard/blob/master/appledoc.rb).

**Comment by tomaz** [comment]
There's 2.2.1 release on https://github.com/tomaz/appledoc/releases, although I should probably update it to include latest fixes with redesigned HTML/CSS (there were updates on that front for a while so wanted to wait a white for things to settle before updating).

**Comment by mkantor** [comment]
Whoops! I was looking through the tags and didn't notice 2.2.1 since it doesn't have a "v" prefix like the other versions. Sorry for the noise!

**Comment by mkantor** [comment]
I noticed an issue with the 2.2.1 release: [the Templates/html directory](https://github.com/tomaz/appledoc/tree/2.2.1/Templates/html) doesn't contain any compiled assets (style.css, index.html, etc are missing). This means that the install-appledoc.sh script doesn't actually work for clean installs.
