### ISSUE TITLE
Not running on OS X 10.7

### ISSUE THREAD

**Issue by azplanlos** [tomaz/appledoc#563]
Appledoc's current version is not running on OS X 10.7 due to a [NSCalendar calendarWithIdentifier:] call which was introduced in 10.9!
When has this been introduced or is it fixable?

Thanks

**Comment by TorreyBetts** [comment]
I added a fix for your issue in my pull request. The following line of code is supported all the way back to OS X 10.4 and does the same thing.

    NSCalendar *gregorian = [[NSCalendar alloc] initWithCalendarIdentifier:NSGregorianCalendar];

**Comment by tomaz** [comment]
Was away for past couple days, so am a bit late with answers... Just merged above PR, so am closing this issue.
