### ISSUE TITLE
Delete homebrew section

### ISSUE THREAD

**Issue by dalinaum** [tomaz/appledoc#568]
`appledoc` is part of `homebrew/boneyard` now. I just visited homebrew/boneyard and saw a shocking phrase. `Archive of formulae removed from the Homebrew package manager`

I think we should delete homebrew section or fix homebrew formula.

refs #567

**Comment by tomaz** [comment]
I'm not sure where homebrew compatibility is right now to be honest - it was contribution, and I never used it myself. There were several complains recently, so I assumed it was taken to "archive" and reflected like that with your PR :) I want to concentrate on appledoc first though, which brings me to shout out for help from contributors - if interested, let me know...

**Comment by dalinaum** [comment]
It looks to me like homebrew formula is not valid anymore. I will try to fix it this weekend.

**Comment by tomaz** [comment]
Thanks!

**Comment by DomT4** [comment]
@kirb resubmitted it to Homebrew core and we accepted it. Was merged back in https://github.com/Homebrew/homebrew/commit/fb54d14e07063215e80eceed8822cf79cd44cf00. You can just do `brew install appledoc` now.

**Comment by dalinaum** [comment]
@DomT4 Great.

**Comment by TorreyBetts** [comment]
I updated the readme's homebrew section. Thanks @DomT4 !
