### ISSUE TITLE
Option to always use bundled templates?

### ISSUE THREAD

**Issue by lumaxis** [tomaz/appledoc#569]
Is there a way to call `appledoc` so it always uses the default templates that are bundled with the binary? We've had some cases where the generated documentation was screwed up because `appledoc` used some legacy template from the user's `~/.appledoc` directory.

**Comment by lumaxis** [comment]
It's been 5 years, so seems like this is not going to get addressed 🙂

**Comment by tomaz** [comment]
Oh, yeah, you're probably right ☺️

But more embarrassing is no reply to your original request, must have slipped past my inbox for some reason...

**Comment by lumaxis** [comment]
Yea, no problem, we've all been there 😄

Feel free to reopen though if you think this is still valuable. I'm just not working with iOS much anymore so don't really have a stake in this.
