### ISSUE TITLE
Split a code block

### ISSUE THREAD

**Issue by marcuseckert** [tomaz/appledoc#585]
Hi,
I have a code block and would like to split it (in order to style it differently later on) without having to add any extra characters in between. Is that possible? I feel like I've tried everything.

**Comment by tomaz** [comment]
Not without adding empty line in between code blocks - it's standard Markdown way of doing things...

**Comment by marcuseckert** [comment]
That is what I'm doing but it doesn't seem to work:

` Build the animation with an SLAnimationInformation object output by <SLReader>.
 
    SLReader *reader = [[SLReader alloc] init];
    NSError* error;
    SLAnimationInformation *animationInformation = [reader parseFileFromBundle:@"myAnimation.sqa" error:&error];
    if (!error) {
        SLSquallAnimation* animation = [[SLSquallAnimation alloc] init];
        [animation buildWithInformation:animationInformation];
        [self.layer addSublayer:animation];
        [animation play];
    } else {
    NSLog(@"error %@", error);
    }
 
 
    let reader = SLReader()
    var animationInformation : SLAnimationInformation?
    do {
        animationInformation = try reader.parseFileFromBundle("myAnimation.sqa")
    } catch {
        print("error \(error)")
    }
    if animationInformation != nil {
        let animation = SLSquallAnimation.init()
        animation.buildWithInformation(animationInfo)
        animation.play()
        self.layer.addSublayer(animation)
    }
 
 
 @param buildInformation	information used to build the animation`

**Comment by tomaz** [comment]
It seems as if that's the same code block. Make sure there's empty line in between (take care of indent, shouldn't be indented). If using tripple backtick, then end previous block and start new one

**Comment by tomaz** [comment]
You might want to test in Markdown editor - if you can get it to display two consequtive code blocks, the same syntax will work with appledoc

**Comment by marcuseckert** [comment]
thanks I'll try that!

**Comment by marcuseckert** [comment]
So, an empty html comment works:
`<!-- tsk -->`
