### ISSUE TITLE
outdated dependencies

### ISSUE THREAD

**Issue by Coeur** [tomaz/appledoc#586]
Appledoc is using:
- [ParseKit](https://github.com/itod/parsekit/) with an older version than 0.0.1 (somewhere around April 2010). There are [4+ newer releases as ParseKit](https://github.com/itod/parsekit/releases), and [15 newer releases as PegKit](https://github.com/itod/pegkit/releases)
- [GRMustache](https://github.com/groue/GRMustache) 7.0.3. Latest is 7.3.2.
- [Discount](https://github.com/Orc/discount) (around version 2.1.5a). Latest is 2.2.0.
- CocoaLumberjack: https://github.com/CocoaLumberjack/CocoaLumberjack
- [RegexKitLite](https://github.com/inquisitiveSoft/RegexKitLite) with version 4.0.1 (January 2016), there is a newer release but without code change
- [DDMiniZip](https://github.com/Daij-Djan/DDMinizip), unmaintained for 4 years, with a dependency on minizip. A direct use of [minizip](https://github.com/nmoinvaz/minizip) would be better.
- [DDCLI](https://github.com/Daij-Djan/DDCLI)
- [DDUtils](https://github.com/Daij-Djan/DDUtils), a small old part of it
- timing.h from [Apple's OpenCL Procedural Grass and Terrain Example](https://developer.apple.com/library/mac/samplecode/OpenCL_Procedural_Grass_and_Terrain_Example/Listings/timing_h.html)
- SynthesizeSingleton from 2009 Matt Gallagher CocoaWithLove. [A variant is given here](https://github.com/steipete/PSFoundation/blob/master/Macros/SynthesizeSingleton.h). But modern implementation should just use the [dispatch_once snippet](https://github.com/cjhanson/Objective-C-Optimized-Singleton)

If @tomaz agree with it, I plan to add a Podfile to the project and move those dependencies to pods, so we can update them with more ease.

**Comment by tomaz** [comment]
Sounds good - although if you want to invest time in appledoc, consider contributing to v3 on development branch instead. Somewhat riskier in terms of releasing it, but more future proof. Just mentioning, your choice :)

**Comment by Coeur** [comment]
I guess I could do it on both branches.

**Comment by tomaz** [comment]
Dependencies setup is only for master, development is completely separate codebase, though I opted for no dependency manager for the moment being. I don't like any of current managers very well; cocoapods alters project/workspace file behind the scenes and carthage has tendendcy to break builds because of incompatibilities in Swift versions. Later should be better with Swift 3.0 though. Also waiting to see how native swift dependencies will fare before deciding on the way to go. That being said, I'm fine with either approach on master...

**Comment by Coeur** [comment]
CocoaLumberJack was customized 5 years ago and never updated since then: https://github.com/tomaz/appledoc/commit/a63d7b54a915e7b02c6b9da39a97417640ba2fb2

@tomaz Can you de-customize it somehow?

**Comment by Coeur** [comment]
I've started CocoaPoding the project: https://github.com/tomaz/appledoc/pull/587

**Comment by tomaz** [comment]
It should be easy to replace CocoaLumberjack - as long as macros and setup code works, it can be simple `printf` behind the scenes. That commit added Xcode support - so that warnings and errors would show up in Xcode and you can click on them to jump to that particular line.

**Comment by Coeur** [comment]
I do not plan to do (by myself) more than what was done. So I'm closing.

**Comment by Coeur** [comment]
But please note that recently I was working on minizip (and ZipArchive), so maybe I can help replacing DMMinizip
