### ISSUE TITLE
Errors running docsetutil when using Xcode 7.3 on CI

### ISSUE THREAD

**Issue by lumaxis** [tomaz/appledoc#590]
I'm currently trying to track down a mysterious error that occurs only when I switch our CI setup on Travis CI to use Xcode 7.3 instead of 7.2.
The "errors" occur sometime while appledoc is trying to run `docsetutil`. This is the log output:

```
DEBUG | GBTask ln 56 > Running command '/usr/bin/xcrun docsetutil index /Users/travis/build/.../docset'
ERROR | GBDocSetOutputGenerator ln 211 > !> 2016-05-03 13:44:36.065 xcodebuild[948:3780] Build settings from command line:
ERROR | GBDocSetOutputGenerator ln 211 > !> 2016-05-03 13:44:36.067 xcodebuild[948:3780]     ENABLE_BITCODE = NO
ERROR | GBDocSetOutputGenerator ln 211 > !> 2016-05-03 13:44:36.068 xcodebuild[948:3780]     SWIFT_DISABLE_REQUIRED_ARCLITE = YES
ERROR | GBDocSetOutputGenerator ln 211 > !> 2016-05-03 13:44:36.069 xcodebuild[948:3780]     SWIFT_LINK_OBJC_RUNTIME = YES
ERROR | GBDocSetOutputGenerator ln 211 > !> 2016-05-03 13:44:36.070 xcodebuild[948:3780]     TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault
ERROR | GBDocSetOutputGenerator ln 211 > !> 2016-05-03 13:44:36.071 xcodebuild[948:3780]     XCODE_DEFAULT_TOOLCHAIN_OVERRIDE = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
```

My current guess is that somehow Xcode 7.3's version of `xcodebuild` outputs unexpected messages that mistakenly get interpreted as errors by appledoc.
I'm not really sure how to debug this further or even fix it so I'll greatly appreciate any hints as how to proceed from here :) Thanks!

**Comment by tomaz** [comment]
They are probably spitted out to stderr, so appledoc thinks it's an error. But they feel like normal logging stuff. And yes, those are Xcode 7.3 specific, I think that's when bitcode was added.

**Comment by lumaxis** [comment]
I've seen this happen with both iOS and tvOS. At least for tvOS, Bitcode has always been there as a requirement since Xcode 7.0 so I'm suspecting some other change in the toolchain.
