### ISSUE TITLE
Document doesn't display in Xcode8

### ISSUE THREAD

**Issue by zxlkungfu** [tomaz/appledoc#612]
Document had been generated, but it doesn't be displayed in Xcode8.

**Comment by Coeur** [comment]
Hello zxlkungfu, and thank you for contacting us.
Xcode 8 has been used by us for almost a year now (I got it from WWDC2016). So could you provide a reproducible example that causes the issue?

**Comment by tomaz** [comment]
You need to restart Xcode after generating docset. Appledoc can install docset to expected folder, but it can't refresh Xcode to pick it up.

**Comment by zxlkungfu** [comment]
@tomaz  Thanks very much.
@Coeur The problem has been solved.
