### ISSUE TITLE
Documentation empty

### ISSUE THREAD

**Issue by neilyoung** [tomaz/appledoc#614]
Well strange. I'm working with appledoc since years. Now I was forced to update a very old project, the very first time since a year. I'm on XCode 8.3 now. The first problem I got was a trap 6 when starting appledoc. I updated the appledoc project from the latest sources, compiled and installed it successfully.

Then I ran appledoc on my project with an inherited old parameter set. The produced HTML files (intermediate files) just contain the framing (headers, links, footers), but not a single content...

I have no clue what has been changed, because the general structure of my source files has not changed at all...

EDIT: I also tried with a very basic command set to no avail.

Any pointer?

**Comment by tomaz** [comment]
This feels like you have outdated templates - replace the files in either `~/.appledoc` or `~/Library/Application Support/appledoc` with latest templates from github (you can also try just deleting those folders, templates come embedded in binary, so depending how you installed appledoc it may work without copying anything)

**Comment by neilyoung** [comment]
Yes, exactly. Have found it right now by myself. Thanks for confirmation. In earlier versions I not even have used a template directory... The ~/Library/Application Support/appledoc directory is non existent here, but I copied the one from your project.

Works.
