### ISSUE TITLE
How can I generate a html docs with the document description unfolding?

### ISSUE THREAD

**Issue by suxinde2009** [tomaz/appledoc#619]
@tomaz 

Hi,  tom

I use appledoc generate a html doc, and when I open the index.html, I found that the document description of class and methods were folding, I have to click the specific method to unfold, it's very troublesome， how could I generate a unfolding doc html with appledoc? Is there any configuration params for this issue?  Thanks for reading :-)

The command I typed is as below:

appledoc --project-name MyProj --project-company "MyCompany" --company-id com.example.test --ignore ThirdParty --output ./Docs --clean-output --create-html --no-create-docset .

**Comment by tomaz** [comment]
You can change templates to suit your needs - depending what you want you can go away with updating CSS, otherwise you'll have to dig into HTML as well, but there's no parameter...

**Comment by suxinde2009** [comment]
@tomaz Thanks for reply.
