### ISSUE TITLE
How to document methods with variable argument lists

### ISSUE THREAD

**Issue by BrunoVandekerkhove** [tomaz/appledoc#621]
When I try to generate documentation for a piece of code, I get a warning that states :

> *(...)* Description for parameter '...' missing for -[*(...)*]!

How can I resolve this?

**Comment by tomaz** [comment]
Writing from memory, but did you try:

```
@param ... description
```

**Comment by BrunoVandekerkhove** [comment]
Yeah, it removes the warning. I thought documenting such methods was done differently but apparently Apple also describes '...' as a param. Thanks.
