### ISSUE TITLE
run    appledoc --project-name DisaterInformation_iOS --project-company bmsoft ./

### ISSUE THREAD

**Issue by wasterd** [tomaz/appledoc#622]
appledoc version: 2.2.1 (build 1334)

WARN: --output argument or global setting not given, will output to current dir '/Users/yaliu/Desktop/DisaterInformation_iOS'!
WARN: --company-id argument or global setting not given, but creating DocSet is enabled, will use 'com.bmsoft.disaterinformation_ios'!
WARN | unsupported typedef enum at Define.h@167!
WARN | unsupported typedef enum at Define.h@175!
WARN | unsupported typedef enum at AFURLRequestSerialization.m@1006!
2017-09-19 10:55:16.471 appledoc[36139:1303730] *** Assertion failure in +[GBMethodData methodDataWithType:result:arguments:], /Users/yaliu/appledoc/Model/GBMethodData.m:44
Oops, something went wrong...
NSInternalInconsistencyException: Invalid parameter not satisfying: [arguments count] >= 1
  @ 0   CoreFoundation                      0x00007fff8b5a72cb __exceptionPreprocess + 171
  @ 1   libobjc.A.dylib                     0x00007fffa03bf48d objc_exception_throw + 48
  @ 2   CoreFoundation                      0x00007fff8b5ac042 +[NSException raise:format:argum

why?

**Comment by tomaz** [comment]
Can't tell from above, but increase verbosity with `--verbose 5` and you should get indication of what it was trying to parse
