### ISSUE TITLE
created html is empty

### ISSUE THREAD

**Issue by duan007a** [tomaz/appledoc#632]
I'm using last version 2.2.1, and output in console like xxxx is not documented. and in doc->class->xxxx.html,there's no comment for property and methods,I don't known what's wrong.

here is my objective-c code
<img width="618" alt="2018-04-10 11 02 59" src="https://user-images.githubusercontent.com/4757625/38534115-04d161de-3caf-11e8-8d69-0769a63ddb47.png">

and here is output xxx.html
<img width="623" alt="2018-04-10 11 03 34" src="https://user-images.githubusercontent.com/4757625/38534136-1c9b05fe-3caf-11e8-8b15-146ed38dc9e9.png">

**Comment by tomaz** [comment]
Assuming the source file is in input path, my next check would be to make sure templates match the version you use (try manually installing them to one of expected paths)

**Comment by duan007a** [comment]
@tomaz Thanks for reply. I install appledoc via Homebrew,and Homebrew does not install templates by default.I manually install them to the path ~/.appledoc
