### ISSUE TITLE
how to ingore all the files in cocoapods?

### ISSUE THREAD

**Issue by liuyankai1990** [tomaz/appledoc#633]
how to ignore all the files in cocoapods? The html  always includes cocoapods's file, e.g. AFNetWorking and SDWebImage etc. i want to know how to ignore the files that in the cocoapods.

**Comment by tomaz** [comment]
Use `-i <path>` option (you can add as many of them as needed - `-i Pods` for example)

When in doubt use `appledic --help` to see list of all options

**Comment by liuyankai1990** [comment]
i used "appledoc -o .doc  --no-create-docset --ignore /Users/liuyankai/Desktop/Project/Pods  --project-name UnionYXF --project-company feel ." to ignore all the files in cocoapods, but it didn't work.   "/Users/Reece/Desktop/Project/Pods" is the cocopods's path. i am new guy,  please don't mind my stupid question.

**Comment by tomaz** [comment]
You don't have to use full path, relative will work just as well and you're free to move your project to different folder too

**Comment by liuyankai1990** [comment]
thanks a lot! i'v already solve the problem.
