### ISSUE TITLE
Expected end of line, but found identifier

### ISSUE THREAD

**Issue by ovidiuvladpop** [tomaz/appledoc#634]
Hello there :)

I am experiencing an issue when I try to generate the Apple-like source code documentation using appledoc. I use Xcode 9.3.1. 

I get this output when I set the verbose to 6:

Finalizing DocSet...
GBDocSetFinalizeGenerator is generating output...
Moving DocSet files from '/Users/ovidiu/ProjectName/docset' to '/Users/ovidiu/Library/Developer/Shared/Documentation/DocSets/ProjectName.docset'...
Initializing directory at '/Users/ovidiu/Library/Developer/Shared/Documentation/DocSets/ProjectName.docset'...
Removing existing directory...
Creating directory...
Moving '/Users/ovidiu/ProjectName/docset' to '/Users/ovidiu/Library/Developer/Shared/Documentation/DocSets/ProjectName.docset'...
Removing '/Users/ovidiu/Library/Developer/Shared/Documentation/DocSets/ProjectName.docset'...
Generation step 4/4: Running GBDocSetInstallGenerator...
Installing DocSet...
GBDocSetInstallGenerator is generating output...
Installing DocSet to Xcode...
Generation step 4/4 failed: GBDocSetInstallGenerator failed generating output, aborting!
Documentation set was installed, but couldn't reload documentation within Xcode.
Expected end of line but found identifier.

Any help will be appreciated !

**Comment by tomaz** [comment]
This is known issue for Xcode 9+, see #628 for discussion

**Comment by ovidiuvladpop** [comment]
Thank you for your answer !
