### ISSUE TITLE
"/!> xcrun:-1: unable to find utility "docsetutil", not a developer tool or in PATH"  in XCode 10

### ISSUE THREAD

**Issue by KsgPhellow** [tomaz/appledoc#635]
Hello, 
I've installed appledoc via brew as per the fact that appledoc seems to be required for the Researchkit.
Sadly I've run into an error:
"/!> xcrun:-1: unable to find utility "docsetutil", not a developer tool or in PATH"

I have not been able to find a proper solution to this, so here's hoping you can shed some light onto this.

Thanks.

**Comment by tomaz** [comment]
docsetutil is no longer available with newer Xcode builds. You should still be able to use appledoc to generate HTML though.

Also some folks managed to install docsetutils from older packages from apple developer downloads page - in case you'd like to try this route...
