### ISSUE TITLE
cross references to instance method of other class

### ISSUE THREAD

**Issue by ErazerControl** [tomaz/appledoc#659]
Hi, Appledoc,
I am fans of AppleDoc. I did some test and found current AppleDoc support that one class can refer to its own methods/properties and other class name. But one class do NOT refer to methods of other classes.
For example, I want to refer ``someMethodInB`` in ``Class A``. But it doesn't been recognized.
```
/**
 * A's description, <someMethodInB>
 */
@interface A 
@end

@interface B
-(void)someMethodInB; 
@end
```
Could you have some solutions about this?

**Comment by tomaz** [comment]
I'm almost certain this is supported, did you try `[B someMethodInB]` or maybe `B.someMethodInB` or something similar? If that doesn't work, check the code, this is likely managed by a regex, so if you can find it and copy it to some online tester, you can then play with various inputs to see what works and what not
